### ISSUE TITLE
Deprecate jquery

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/friskby#114]
As I see it, there is no reason to use JQuery.

**Comment by oyta** [comment]
I do not agree. Bootstrap is dependent on jQuery for javascript plugins. And in addition jQuery will be good to use for our own javacript that we will implement for interaction.

**Comment by pgdr** [comment]
Let's discuss this in greater detail, later.  I think that we should cut down on external libraries for now, and start introducing them when we see that we cannot do without them.

For instance, I believe that bootstrap could be removed quite easily and replaced with pure CSS.

Do we need all of the following?
* proj4
* openlayers
* leaflet

What do you think we need from JQuery for interaction?  Can't we just use plain js (and XmlHttpRequest)?

**Comment by oyta** [comment]
If anything, jQuery makes things easier and less complex code. I do not see the big benefits of removing it. We have to make it easy and maintainable as there are limited resources on development. But of course, we can discuss it.

- Bootstrap: Bootstrap makes the entire page responsive and makes it easy to build.
- proj4: Yes - transforming coordinates. Why should we remove it?
- openlayers: The map
- leaflet: No - this should have been removed. It is not used anymore.

All in all - I am not sure why you want to remove all the libraries. They are commonly used libraries throughout the internet. If you think we should drop them due to performance, I think we should do what we have been taking about developing on the server side first. That is what makes the big difference as I see it.

**Comment by pgdr** [comment]
Okay, I yield—let's fix the api and use django for what it's worth.

However, I believe (and hope) that when the API is fixed, we will realize that we don't need bootstrap (nor proj4).
